apiVersion: skaffold/v4beta13
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: ticketing-dev-460601
  artifacts:
    - image: markbastoulis/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: markbastoulis/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: ' **/*.ts'
            dest: .
